---
- name: Rename System Drive
  ansible.windows.win_powershell:
    script: |
      [string]$SystemDriveLetter = ($env:SYSTEMDRIVE).TrimEnd(":")
      Set-Volume -DriveLetter $SystemDriveLetter -NewFileSystemLabel "System Drive"

- name: Set local administrator password to never expire
  ansible.windows.win_powershell:
    script: |
      wmic useraccount WHERE Name='vagrant' set PasswordExpires=false

- name: Disable 'IE Enhanced Security Configuration' for all users
  ansible.windows.win_regedit:
    path: '{{ item }}'
    name: IsInstalled
    data: 0
  loop:
    - HKLM:\SOFTWARE\Microsoft\Active Setup\Installed Components
    - HKLM:\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A7-37EF-4b3f-8CFC-4F3A74704073}
    - HKLM:\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A8-37EF-4b3f-8CFC-4F3A74704073}

- name: Delete installation directories
  ansible.windows.win_file:
    path: '{{ item }}'
    state: absent
  loop:
    - 'c:\Install'
    - 'c:\Script'
    - 'c:\Log'
    - 'c:\Logs'
    - 'c:\GPO'

- name: Create files directory
  ansible.windows.win_file:
    path: 'c:\files'
    state: directory

- name: Copy files to files directory
  ansible.windows.win_copy:
    src: files/*
    dest: 'c:\files\'

- name: Reboot
  win_reboot: